<a href="https://colab.research.google.com/github/GameLooped/ExamenFinal/blob/main/Examen_final.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Parte 1

In [7]:
import numpy as np

arreglo = np.arange(1, 21)

print(arreglo)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [8]:
multiplos_de_3 = arreglo[arreglo % 3 == 0]

print(multiplos_de_3)

[ 3  6  9 12 15 18]


In [20]:
num_aleatorios = np.random.rand(5, 5)

print(num_aleatorios)

[[0.15885526 0.85417104 0.77036144 0.34617806 0.1181759 ]
 [0.11011032 0.80462951 0.83159016 0.91682961 0.48643347]
 [0.62383315 0.24630441 0.5393284  0.5455691  0.9379289 ]
 [0.29323854 0.59123955 0.70118104 0.97838253 0.86961435]
 [0.8929541  0.43879896 0.61321515 0.04338362 0.77299379]]


In [15]:
media = num_aleatorios.mean()
desviacion_estandar = num_aleatorios.std()
valor_maximo = num_aleatorios.max()

print(f"Media: {media}")
print(f"Desviación Estándar: {desviacion_estandar}")
print(f"Valor Máximo: {valor_maximo}")

Media: 0.535078333787449
Desviación Estándar: 0.27484656896995546
Valor Máximo: 0.9952442595508969


In [21]:
vector = num_aleatorios.flatten()

print(vector)

[0.15885526 0.85417104 0.77036144 0.34617806 0.1181759  0.11011032
 0.80462951 0.83159016 0.91682961 0.48643347 0.62383315 0.24630441
 0.5393284  0.5455691  0.9379289  0.29323854 0.59123955 0.70118104
 0.97838253 0.86961435 0.8929541  0.43879896 0.61321515 0.04338362
 0.77299379]


Parte 2

In [23]:
import pandas as pd

datos_estudiantes = {
    'Nombre': ['Ana', 'Luis', 'María', 'Pedro', 'Sofía'],
    'Edad': [20, 21, 19, 22, 20],
    'Nota Matemáticas': [18, 15, 16, 12, 19],
    'Nota IA': [17, 14, 18, 13, 20]
}

df_estudiantes = pd.DataFrame(datos_estudiantes)
print(df_estudiantes)

  Nombre  Edad  Nota Matemáticas  Nota IA
0    Ana    20                18       17
1   Luis    21                15       14
2  María    19                16       18
3  Pedro    22                12       13
4  Sofía    20                19       20


In [25]:
promedios_numericos = df_estudiantes.select_dtypes(include='number').mean()
print(promedios_numericos)

Edad                20.4
Nota Matemáticas    16.0
Nota IA             16.4
dtype: float64


In [28]:
estudiantes_filtrados = df_estudiantes[df_estudiantes['Nota IA'] > 15]
print(estudiantes_filtrados)

  Nombre  Edad  Nota Matemáticas  Nota IA  Promedio
0    Ana    20                18       17      17.5
2  María    19                16       18      17.0
4  Sofía    20                19       20      19.5


In [29]:
df_estudiantes['Promedio'] = df_estudiantes[['Nota Matemáticas', 'Nota IA']].mean(axis=1)
print(df_estudiantes)

  Nombre  Edad  Nota Matemáticas  Nota IA  Promedio
0    Ana    20                18       17      17.5
1   Luis    21                15       14      14.5
2  María    19                16       18      17.0
3  Pedro    22                12       13      12.5
4  Sofía    20                19       20      19.5


In [30]:
df_ordenado = df_estudiantes.sort_values(by='Promedio', ascending=False)
print(df_ordenado)

  Nombre  Edad  Nota Matemáticas  Nota IA  Promedio
4  Sofía    20                19       20      19.5
0    Ana    20                18       17      17.5
2  María    19                16       18      17.0
1   Luis    21                15       14      14.5
3  Pedro    22                12       13      12.5


Parte 3

In [40]:
def analizar_lista(numeros):
    if not numeros:
        return None, None, None

    mayor = max(numeros)
    menor = min(numeros)
    promedio = sum(numeros) / len(numeros)

    return mayor, menor, promedio

mi_lista = [45, 40, 8, 22, 70, 11]
num_mayor, num_menor, promedio = analizar_lista(mi_lista)

print(f"Lista original: {mi_lista}")
print(f"Número mayor: {num_mayor}")
print(f"Número menor: {num_menor}")
print(f"Promedio: {promedio}")

Lista original: [45, 40, 8, 22, 70, 11]
Número mayor: 70
Número menor: 8
Promedio: 32.666666666666664


In [44]:
import numpy as np

def sigmoide(x):

  return 1 / (1 + np.exp(-x))

x = np.array([-2, -1, 0, 1, 2])

resultado_sigmoide = sigmoide(x)

print(f"Arreglo original: {x}")
print(f"Resultado de la función Sigmoide: {resultado_sigmoide}")

Arreglo original: [-2 -1  0  1  2]
Resultado de la función Sigmoide: [0.11920292 0.26894142 0.5        0.73105858 0.88079708]


In [46]:
import pandas as pd
datos_estudiantes = {
    'Nombre': ['Ana', 'Luis', 'María', 'Pedro', 'Sofía'], 'Edad': [20, 21, 19, 22, 20],
    'Nota Matemáticas': [18, 15, 16, 12, 19], 'Nota IA': [17, 14, 18, 13, 20]
}
df_estudiantes = pd.DataFrame(datos_estudiantes)
df_estudiantes['Promedio'] = df_estudiantes[['Nota Matemáticas', 'Nota IA']].mean(axis=1)

def clasificar_estado(promedio):
    if promedio >= 14:
        return "Aprobado"
    else:
        return "Desaprobado"

df_estudiantes['Estado'] = df_estudiantes['Promedio'].apply(clasificar_estado)

print(df_estudiantes)

  Nombre  Edad  Nota Matemáticas  Nota IA  Promedio       Estado
0    Ana    20                18       17      17.5     Aprobado
1   Luis    21                15       14      14.5     Aprobado
2  María    19                16       18      17.0     Aprobado
3  Pedro    22                12       13      12.5  Desaprobado
4  Sofía    20                19       20      19.5     Aprobado


Parte 4

In [48]:
import pandas as pd

datos = {
    'Producto': ['A', 'B', 'C', 'D', 'E'],
    'Ventas_2024': [120, 340, 560, 230, 150],
    'Ventas_2025': [200, 400, 600, 300, 180]
}
df = pd.DataFrame(datos)
df['Crecimiento'] = ((df['Ventas_2025'] - df['Ventas_2024']) / df['Ventas_2024']) * 100
print(df)

  Producto  Ventas_2024  Ventas_2025  Crecimiento
0        A          120          200    66.666667
1        B          340          400    17.647059
2        C          560          600     7.142857
3        D          230          300    30.434783
4        E          150          180    20.000000


In [50]:
indice_max_crecimiento = df['Crecimiento'].idxmax()
producto_mayor_crecimiento = df.loc[indice_max_crecimiento]

print("El producto con mayor crecimiento es:")
print(producto_mayor_crecimiento)

El producto con mayor crecimiento es:
Producto               A
Ventas_2024          120
Ventas_2025          200
Crecimiento    66.666667
Name: 0, dtype: object


Parte 5

In [55]:
def resolver_ecuacion_primer_grado(a, b):

    if a == 0:
        if b == 0:
            return "La ecuación tiene infinitas soluciones."
        else:
            return "La ecuación no tiene solución."
    else:
        x = -b / a
        return x

a = 2
b = 4
solucion = resolver_ecuacion_primer_grado(a, b)
print(f"La solución para la ecuación {a}x + {b} = 0 es x = {solucion}")

La solución para la ecuación 2x + 4 = 0 es x = -2.0


In [57]:
import numpy as np

def resolver_ecuacion_segundo_grado(a, b, c):
    if a == 0:
        return "El coeficiente 'a' no puede ser cero para una ecuación de segundo grado."

    discriminante = (b**2) - (4*a*c)

    x1 = (-b - np.sqrt(discriminante + 0j)) / (2 * a)
    x2 = (-b + np.sqrt(discriminante + 0j)) / (2 * a)

    return x1, x2

a = 1
b = 2
c = 5
solucion1, solucion2 = resolver_ecuacion_segundo_grado(a, b, c)

print(f"Las soluciones para la ecuación {a}x^2 + {b}x + {c} = 0 son:")
print(f"x1 = {solucion1}")
print(f"x2 = {solucion2}")

Las soluciones para la ecuación 1x^2 + 2x + 5 = 0 son:
x1 = (-1-2j)
x2 = (-1+2j)
